### ISSUE TITLE
Include Iterator from Wild/Wyss

### ISSUE THREAD

**Issue by Dierk** [WebEngineering-FHNW/Kolibri#13]

**Comment by Dierk** [comment]
sequence lib is included

**Comment by affolter** [comment]
Lieber Dierk

So fleissig wie immer. :-)

Ich habe erneut über die großartige Session nachgedacht. Nun bin ich zu dem Schluss gekommen, dass es aus zwei Gründen möglicherweise besser wäre, das Control, das du das letzte Mal erstellt hast, erneut zu verwenden. Obwohl die Spielidee interessant ist und die SBB-Kacheln ihren Reiz haben, denke ich aus folgenden Gründen, dass die Variante mit der Zeiteingabe vielleicht besser geeignet sein könnte:

Erstens: Die Problematik ist für jeden sofort verständlich - Zeiteingabe.
Zweitens: Du hast bereits Erfahrung und weißt ungefähr, wo die Studierenden Probleme haben werden. Dadurch können sie gezielter unterstützt werden, und der Umfang und Aufwand sind besser abschätzbar. Das Custom Control bietet eine große Vielfalt an Gestaltungsmöglichkeiten, nahezu unbegrenzte. Das Besondere daran ist, dass ich denke, dass die Aufgabe auf mindestens acht verschiedene Arten gelöst werden kann. Vielleicht könnten wir sogar eine unterhaltsame Variante hinzufügen, als Inspiration für die Studierenden. :-)

Drittens: Da dies hoffentlich nicht unser letzter Workshop ist, könnten wir für den nächsten genug oder sogar mehr Zeit haben, um über etwas Neues nachzudenken?

Was hältst du von meinen Punkten?

Liebe Grüsse
Fabian


Zu den Terminen.

W1 versuche ich mindestens eine Stunde online dabei zu sein. Wenn das für dich passt.
W2 kann ich definitiv vor Ort sein

Voraussichtlich
W3 auch vor Ort und W4 dann online

W5 definitiv vor Ort




On 12 Sep 2023, at 16:04, Dierk König ***@***.******@***.***>> wrote:


Closed #13 as completed.
