### ISSUE TITLE
Old Version of LambdaCalculus Repo in contrib folder

### ISSUE THREAD

**Issue by BenjaminBrodwolf** [WebEngineering-FHNW/Kolibri#2]
In the [contrib folder](https://github.com/WebEngineering-FHNW/Kolibri/tree/main/contrib/p6_brodwolf_andermatt) is an old and unfinished version of the project "LambdaCalculus with JS" from P. Andermatt & B.Brodwolf copied.

**Comment by BenjaminBrodwolf** [comment]
- [ ] PR is merged for update the project folder: https://github.com/WebEngineering-FHNW/Kolibri/pull/3

**Comment by Dierk** [comment]
merged - thanks for the update!
